steps:
  - name: "gcr.io/cloud-builders/npm"
    args: ["install"]
    dir: "www"
  - name: "gcr.io/cloud-builders/npm"
    args: ["run", "test"]
    dir: "www"
  - name: "gcr.io/cloud-builders/go"
    args: ["build"]
    env: ["PROJECT_ROOT=api"]
    dir: "main"
  - name: "gcr.io/cloud-builders/go"
    args: ["test", "./..."]
    env: ["PROJECT_ROOT=api"]
