steps:
  - name: "gcr.io/cloud-builders/npm"
    args: ["install"]
    dir: "www"
  - name: "gcr.io/cloud-builders/npm"
    args: ["run", "test"]
    dir: "www"
  - name: mirror.gcr.io/library/golang
    env:
      - GO111MODULE=on
    args: ["go", "build", "./..."]
    dir: "api"
    volumes:
      - name: go-modules
        path: /go
  - name: mirror.gcr.io/library/golang
    env:
      - GO111MODULE=on
    args: ["go", "test", "./..."]
    dir: "api"
    volumes:
      - name: go-modules
        path: /go
